#define _GNU_SOURCE
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <signal.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <linux/limits.h>
#include "zdtmtst.h"
#include "map_f.h"
#include <stdarg.h>

const char *test_doc	= "Test shared memory";

/*
 *
 *                        [            ROOT                    ]
 * 	                      /            |                       \
 * 	                 CHILD1		       [    CHILD7  ]           CHILD11
 *                  /     \			  /      |       \                \
 *            CHILD2      CHILD6	 CHILD8  CHILD9   CHILD10      CHILD12
 *           /                                                          \
 *     CHILD3                                                           CHILD13
 *    /      \
 *   CHILD4  CHILD5
 */

int main(int argc, char ** argv)
{
	INIT(ROOT, argc, argv);


	/* ROOT */
#define ROOT_MEM_SIZE PAGE_SIZE * 30

	void * ROOT_MEM;

	MMAP(ROOT, ROOT_MEM, NULL, ROOT_MEM_SIZE, PROT_WRITE | PROT_READ,
			MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	FORK(ROOT, CHILD1);
	FORK(ROOT, CHILD7);
	FORK(ROOT, CHILD11);

	MUNMAP(ROOT, ROOT_MEM, ROOT_MEM_SIZE);

	/* CHILD1 */
#define CHILD1_MEM1_OFFSET PAGE_SIZE
#define CHILD1_MEM1_SIZE   PAGE_SIZE * 10

	void * CHILD1_MEM1 = MAP_FAILED;
	void * RESERVED;
	MMAP(CHILD1, RESERVED, NULL, CHILD1_MEM1_SIZE, PROT_WRITE | PROT_READ,
			MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD1, CHILD1_MEM1, (ROOT_MEM + CHILD1_MEM1_OFFSET),
								CHILD1_MEM1_SIZE,
								CHILD1_MEM1_SIZE,
								MREMAP_MAYMOVE | MREMAP_FIXED,
								RESERVED);


#define CHILD1_MEM2_OFFSET PAGE_SIZE * 29
#define CHILD1_MEM2_SIZE   PAGE_SIZE
	void * CHILD1_MEM2 = MAP_FAILED;
	MMAP(CHILD1, RESERVED, NULL, CHILD1_MEM2_SIZE, PROT_WRITE | PROT_READ,
				MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD1, CHILD1_MEM2, (ROOT_MEM + CHILD1_MEM2_OFFSET),
								CHILD1_MEM2_SIZE,
								CHILD1_MEM2_SIZE,
								MREMAP_MAYMOVE | MREMAP_FIXED,
								RESERVED);

	FORK(CHILD1, CHILD2);
	FORK(CHILD1, CHILD6);
	MUNMAP(CHILD1, ROOT_MEM, CHILD1_MEM1_OFFSET);
	MUNMAP(CHILD1, (ROOT_MEM + (CHILD1_MEM1_OFFSET + CHILD1_MEM1_SIZE) ),
			(CHILD1_MEM2_OFFSET - (CHILD1_MEM1_OFFSET + CHILD1_MEM1_SIZE)));

	/* CHILD6 */
#define CHILD6_MEM1_OFFSET PAGE_SIZE * 2
#define CHILD6_MEM1_SIZE PAGE_SIZE * 2
#define CHILD6_MEM2_OFFSET 0
#define CHILD6_MEM2_SIZE PAGE_SIZE * 2

	void * CHILD6_MEM1 = MAP_FAILED,
			*CHILD6_MEM2 = MAP_FAILED;
	MMAP(CHILD6, RESERVED, NULL, CHILD6_MEM1_SIZE, PROT_WRITE | PROT_READ,
						MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD6, CHILD6_MEM1, (CHILD1_MEM1 + CHILD6_MEM1_OFFSET),
								CHILD6_MEM1_SIZE,
								CHILD6_MEM1_SIZE,
								MREMAP_MAYMOVE | MREMAP_FIXED,
								RESERVED);
	MMAP(CHILD6, RESERVED, NULL, CHILD6_MEM2_SIZE, PROT_WRITE | PROT_READ,
							MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD6, CHILD6_MEM2, (CHILD1_MEM1 + CHILD6_MEM2_OFFSET),
								CHILD6_MEM2_SIZE,
								CHILD6_MEM2_SIZE,
								MREMAP_MAYMOVE | MREMAP_FIXED,
								RESERVED);


	/* CHILD2 */
#define CHILD2_MEM1_OFFSET 0
#define CHILD2_MEM1_SIZE 5 * PAGE_SIZE
#define CHILD2_MEM2_OFFSET 5 * PAGE_SIZE
#define CHILD2_MEM2_SIZE 5 * PAGE_SIZE
	void * CHILD2_MEM1, * CHILD2_MEM2;

	MMAP(CHILD2, RESERVED, NULL, CHILD2_MEM1_SIZE, PROT_WRITE | PROT_READ,
					MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD2, CHILD2_MEM1, (CHILD1_MEM1 + CHILD2_MEM1_OFFSET),
								CHILD2_MEM1_SIZE,
								CHILD2_MEM1_SIZE,
								MREMAP_MAYMOVE | MREMAP_FIXED,
								RESERVED);

	MMAP(CHILD2, RESERVED, NULL, CHILD2_MEM2_SIZE, PROT_WRITE | PROT_READ,
						MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD2, CHILD2_MEM2, (CHILD1_MEM1 + CHILD2_MEM2_OFFSET),
									CHILD2_MEM2_SIZE,
									CHILD2_MEM2_SIZE,
									MREMAP_MAYMOVE | MREMAP_FIXED,
									RESERVED);

	FORK(CHILD2, CHILD3);
	/* CHILD3 */
#define CHILD3_MEM1_OFFSET 0
#define CHILD3_MEM1_SIZE PAGE_SIZE * 2
#define CHILD3_MEM2_OFFSET PAGE_SIZE * 2
#define CHILD3_MEM2_SIZE PAGE_SIZE * 2
	void * CHILD3_MEM1 = MAP_FAILED,
			* CHILD3_MEM2 = MAP_FAILED;
	MMAP(CHILD3, RESERVED, NULL, CHILD3_MEM1_SIZE, PROT_WRITE | PROT_READ,
						MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD3, CHILD3_MEM1, (CHILD2_MEM1 + CHILD3_MEM1_OFFSET),
									CHILD3_MEM1_SIZE,
									CHILD3_MEM1_SIZE,
									MREMAP_MAYMOVE | MREMAP_FIXED,
									RESERVED);

	MMAP(CHILD3, RESERVED, NULL, CHILD3_MEM2_SIZE, PROT_WRITE | PROT_READ,
							MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD3, CHILD3_MEM2, (CHILD2_MEM1 + CHILD3_MEM2_OFFSET),
										CHILD3_MEM2_SIZE,
										CHILD3_MEM2_SIZE,
										MREMAP_MAYMOVE | MREMAP_FIXED,
										RESERVED);

	FORK(CHILD3, CHILD4);
	/* CHILD4 */
#define CHILD4_MEM1_OFFSET PAGE_SIZE
#define CHILD4_MEM1_SIZE PAGE_SIZE * 2
#define CHILD4_MEM2_OFFSET PAGE_SIZE * 3
#define CHILD4_MEM2_SIZE PAGE_SIZE * 2
	void * CHILD4_MEM1 = MAP_FAILED,
			* CHILD4_MEM2 = MAP_FAILED;
	MMAP(CHILD4, RESERVED, NULL, CHILD4_MEM1_SIZE, PROT_WRITE | PROT_READ,
						MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD4, CHILD4_MEM1, (CHILD2_MEM2 + CHILD4_MEM1_OFFSET),
									CHILD4_MEM1_SIZE,
									CHILD4_MEM1_SIZE,
									MREMAP_MAYMOVE | MREMAP_FIXED,
									RESERVED);

	MMAP(CHILD4, RESERVED, NULL, CHILD4_MEM2_SIZE, PROT_WRITE | PROT_READ,
							MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD4, CHILD4_MEM2, (CHILD2_MEM2 + CHILD4_MEM2_OFFSET),
										CHILD4_MEM2_SIZE,
										CHILD4_MEM2_SIZE,
										MREMAP_MAYMOVE | MREMAP_FIXED,
										RESERVED);
	FORK(CHILD3, CHILD5);
	/* CHILD 5 */
#define CHILD5_MEM1_OFFSET PAGE_SIZE
#define CHILD5_MEM1_SIZE PAGE_SIZE * 2
#define CHILD5_MEM2_OFFSET PAGE_SIZE * 3
#define CHILD5_MEM2_SIZE PAGE_SIZE * 2
	void * CHILD5_MEM1 = MAP_FAILED,
			* CHILD5_MEM2 = MAP_FAILED;
	MMAP(CHILD5, RESERVED, NULL, CHILD5_MEM1_SIZE, PROT_WRITE | PROT_READ,
						MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD5, CHILD5_MEM1, (CHILD2_MEM2 + CHILD5_MEM1_OFFSET),
									CHILD5_MEM1_SIZE,
									CHILD5_MEM1_SIZE,
									MREMAP_MAYMOVE | MREMAP_FIXED,
									RESERVED);

	MMAP(CHILD5, RESERVED, NULL, CHILD5_MEM2_SIZE, PROT_WRITE | PROT_READ,
							MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD5, CHILD5_MEM2, (CHILD2_MEM2 + CHILD5_MEM2_OFFSET),
										CHILD5_MEM2_SIZE,
										CHILD5_MEM2_SIZE,
										MREMAP_MAYMOVE | MREMAP_FIXED,
										RESERVED);
	/* CHILD7 */
#define CHILD7_MEM1_OFFSET PAGE_SIZE * 29
#define CHILD7_MEM1_SIZE PAGE_SIZE
#define CHILD7_MEM2_OFFSET PAGE_SIZE
#define CHILD7_MEM2_SIZE PAGE_SIZE * 10

	void * CHILD7_MEM1 = MAP_FAILED,
			* CHILD7_MEM2 = MAP_FAILED;
	MMAP(CHILD7, RESERVED, NULL, CHILD7_MEM1_SIZE, PROT_WRITE | PROT_READ,
						MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD7, CHILD7_MEM1, (ROOT_MEM + CHILD7_MEM1_OFFSET),
									CHILD7_MEM1_SIZE,
									CHILD7_MEM1_SIZE,
									MREMAP_MAYMOVE | MREMAP_FIXED,
									RESERVED);
	MMAP(CHILD7, RESERVED, NULL, CHILD7_MEM2_SIZE, PROT_WRITE | PROT_READ,
								MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD7, CHILD7_MEM2, (ROOT_MEM + CHILD7_MEM2_OFFSET),
										CHILD7_MEM2_SIZE,
										CHILD7_MEM2_SIZE,
										MREMAP_MAYMOVE | MREMAP_FIXED,
										RESERVED);
	FORK(CHILD7, CHILD8);
	/* CHILD 8 */
#define CHILD8_MEM1_OFFSET 0
#define CHILD8_MEM1_SIZE PAGE_SIZE * 2
#define CHILD8_MEM2_OFFSET PAGE_SIZE * 2
#define CHILD8_MEM2_SIZE PAGE_SIZE * 2

	void * CHILD8_MEM1 = MAP_FAILED,
			* CHILD8_MEM2 = MAP_FAILED;
	MMAP(CHILD8, RESERVED, NULL, CHILD8_MEM1_SIZE, PROT_WRITE | PROT_READ,
						MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD8, CHILD8_MEM1, (CHILD7_MEM2 + CHILD8_MEM1_OFFSET),
									CHILD8_MEM1_SIZE,
									CHILD8_MEM1_SIZE,
									MREMAP_MAYMOVE | MREMAP_FIXED,
									RESERVED);
	MMAP(CHILD8, RESERVED, NULL, CHILD8_MEM2_SIZE, PROT_WRITE | PROT_READ,
								MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD8, CHILD8_MEM2, (CHILD7_MEM2 + CHILD8_MEM2_OFFSET),
										CHILD8_MEM2_SIZE,
										CHILD8_MEM2_SIZE,
										MREMAP_MAYMOVE | MREMAP_FIXED,
										RESERVED);
	FORK(CHILD7, CHILD9);
	/* CHILD 9 */
#define CHILD9_MEM1_OFFSET PAGE_SIZE * 6
#define CHILD9_MEM1_SIZE PAGE_SIZE * 2
	void * CHILD9_MEM1 = MAP_FAILED;
	MMAP(CHILD9, RESERVED, NULL, CHILD9_MEM1_SIZE, PROT_WRITE | PROT_READ,
						MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD9, CHILD9_MEM1, (CHILD7_MEM2 + CHILD9_MEM1_OFFSET),
									CHILD9_MEM1_SIZE,
									CHILD9_MEM1_SIZE,
									MREMAP_MAYMOVE | MREMAP_FIXED,
									RESERVED);
	FORK(CHILD7, CHILD10);
	/* CHILD 10 */
#define CHILD10_MEM1_OFFSET PAGE_SIZE * 8
#define CHILD10_MEM1_SIZE PAGE_SIZE * 2
	void * CHILD10_MEM1 = MAP_FAILED;
	MMAP(CHILD10, RESERVED, NULL, CHILD10_MEM1_SIZE, PROT_WRITE | PROT_READ,
						MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD10, CHILD10_MEM1, (CHILD7_MEM2 + CHILD10_MEM1_OFFSET),
									CHILD10_MEM1_SIZE,
									CHILD10_MEM1_SIZE,
									MREMAP_MAYMOVE | MREMAP_FIXED,
									RESERVED);

	/* CHILD11 */
#define CHILD11_MEM1_OFFSET PAGE_SIZE * 27
#define CHILD11_MEM1_SIZE PAGE_SIZE * 3
	void * CHILD11_MEM1 = MAP_FAILED;
	MMAP(CHILD11, RESERVED, NULL, CHILD11_MEM1_SIZE, PROT_WRITE | PROT_READ,
						MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD11, CHILD11_MEM1, (ROOT_MEM + CHILD11_MEM1_OFFSET),
									CHILD11_MEM1_SIZE,
									CHILD11_MEM1_SIZE,
									MREMAP_MAYMOVE | MREMAP_FIXED,
									RESERVED);

	FORK(CHILD11, CHILD12);
	/*CHILD12 */
	FORK(CHILD12, CHILD13);
	MUNMAP(CHILD12, CHILD11_MEM1, CHILD11_MEM1_SIZE);
	/* CHILD13 */
#define CHILD13_MEM1_OFFSET PAGE_SIZE * 2
#define CHILD13_MEM1_SIZE PAGE_SIZE
	void * CHILD13_MEM1 = MAP_FAILED;
	MMAP(CHILD13, RESERVED, NULL, CHILD13_MEM1_SIZE, PROT_WRITE | PROT_READ,
						MAP_SHARED | MAP_ANONYMOUS, -1, 0);

	MREMAP(CHILD13, CHILD13_MEM1, (CHILD11_MEM1 + CHILD13_MEM1_OFFSET),
									CHILD13_MEM1_SIZE,
									CHILD13_MEM1_SIZE,
									MREMAP_MAYMOVE | MREMAP_FIXED,
									RESERVED);
	/* DATAGEN */
	uint32_t crc;
	DATAGEN_Z(CHILD5, crc, CHILD5_MEM1, CHILD5_MEM1_SIZE);

	DATAGEN_Z(CHILD4, crc, CHILD4_MEM2, CHILD4_MEM2_SIZE);

	DATAGEN_Z(CHILD6, crc, CHILD6_MEM1, CHILD6_MEM1_SIZE);

	DATAGEN_Z(CHILD5, crc, CHILD3_MEM1, CHILD3_MEM1_SIZE);

	DATAGEN_Z(CHILD13, crc, CHILD13_MEM1, CHILD13_MEM1_SIZE);

	/* CRIU START */
	CR_START(ROOT);

	/* DATACHK */
	DATACHK_Z_CHECK(CHILD4, crc, CHILD4_MEM1, CHILD4_MEM1_SIZE);
	DATACHK_Z_CHECK(CHILD5, crc, CHILD5_MEM1, CHILD5_MEM1_SIZE);
	DATACHK_Z_CHECK(CHILD9, crc, CHILD9_MEM1, CHILD9_MEM1_SIZE);

	DATACHK_Z_CHECK(CHILD4, crc, CHILD4_MEM2, CHILD4_MEM2_SIZE);
	DATACHK_Z_CHECK(CHILD5, crc, CHILD5_MEM2, CHILD5_MEM2_SIZE);
	DATACHK_Z_CHECK(CHILD10, crc, CHILD10_MEM1, CHILD10_MEM1_SIZE);

	DATACHK_Z_CHECK(CHILD6, crc, CHILD6_MEM1, CHILD6_MEM1_SIZE);
	DATACHK_Z_CHECK(CHILD3, crc, CHILD3_MEM2, CHILD3_MEM2_SIZE);
	DATACHK_Z_CHECK(CHILD4, crc, CHILD3_MEM2, CHILD3_MEM2_SIZE);
	DATACHK_Z_CHECK(CHILD5, crc, CHILD3_MEM2, CHILD3_MEM2_SIZE);
	DATACHK_Z_CHECK(CHILD8, crc, CHILD8_MEM2, CHILD8_MEM2_SIZE);

	DATACHK_Z_CHECK(CHILD6, crc, CHILD6_MEM2, CHILD6_MEM2_SIZE);
	DATACHK_Z_CHECK(CHILD3, crc, CHILD3_MEM1, CHILD3_MEM1_SIZE);
	DATACHK_Z_CHECK(CHILD4, crc, CHILD3_MEM1, CHILD3_MEM1_SIZE);
	DATACHK_Z_CHECK(CHILD5, crc, CHILD3_MEM1, CHILD3_MEM1_SIZE);
	DATACHK_Z_CHECK(CHILD8, crc, CHILD8_MEM1, CHILD8_MEM1_SIZE);


	DATACHK_Z_CHECK(CHILD13, crc, CHILD13_MEM1, CHILD13_MEM1_SIZE);
	DATACHK_Z_CHECK(CHILD11, crc, (CHILD11_MEM1 + CHILD13_MEM1_OFFSET), CHILD13_MEM1_SIZE);
	DATACHK_Z_CHECK(CHILD5, crc, CHILD1_MEM2, CHILD1_MEM2_SIZE);
	DATACHK_Z_CHECK(CHILD4, crc, CHILD1_MEM2, CHILD1_MEM2_SIZE);
	DATACHK_Z_CHECK(CHILD3, crc, CHILD1_MEM2, CHILD1_MEM2_SIZE);
	DATACHK_Z_CHECK(CHILD2, crc, CHILD1_MEM2, CHILD1_MEM2_SIZE);
	DATACHK_Z_CHECK(CHILD1, crc, CHILD1_MEM2, CHILD1_MEM2_SIZE);
	DATACHK_Z_CHECK(CHILD7, crc, CHILD7_MEM1, CHILD7_MEM1_SIZE);
	DATACHK_Z_CHECK(CHILD8, crc, CHILD7_MEM1, CHILD7_MEM1_SIZE);
	DATACHK_Z_CHECK(CHILD9, crc, CHILD7_MEM1, CHILD7_MEM1_SIZE);
	DATACHK_Z_CHECK(CHILD10, crc, CHILD7_MEM1, CHILD7_MEM1_SIZE);


	FINIT(ROOT);
}
